config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  devise_for :users

  namespace :backend do
    root to: 'dashboard#index'
    get :dashboard, to: 'dashboard#index'
    resource :profile, only: [:show, :update, :destroy] do
      get :account_setting
    end
    resources :charity_locations do
      resources :charities
    end

    resources :package_costs

    resources :donations do
      get "sync" => "donations#sync", as: :sync
    end

    resources :users do
      member do
        post :notification_modal
        post :push_notification
      end
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',  controllers: {
        confirmations:      'devise_overrides/confirmations',
        passwords:          'devise_overrides/passwords',
        omniauth_callbacks: 'devise_overrides/omniauth_callbacks',
        registrations:      'devise_overrides/registrations',
        sessions:           'devise_overrides/sessions',
        token_validations:  'devise_overrides/token_validations'
      }

      controller :registrations do
        post :facebook, path: 'auth/facebook'
        post :twitter, path: 'auth/twitter'
      end

      resource :profile, only: [:show, :update] do
        collection do
        end
      end

      resources :addresses do
        collection do
        end
      end

      resources :donations do
        collection do
          get :total_donations, path: "total"
        end
      end

      resources :charity_locations, only: [:index] do
        collection do
          resources :charities
          get 'charities' => 'charities#index' 
        end
      end


      resources :donation_categories, only: [:index] do
        collection do
        end
      end

      resources :package_costs, only: [:index] do
        collection do
        end
      end

    end
    match "*path", to: "base#render_endpoint_not_exists", via: :all
  end

  controller :home do
    get :welcome, path: 'pages/welcome'
  end

  # match "*path", to: "home#render_404", via: :get
end

app/views/shared/_backend_sidebar.html.haml
.navbar-default.sidebar.nicescroll{:role => "navigation"}
  .sidebar-nav.navbar-collapse
    %ul#side-menu.nav
      %li.sidebar-search.hidden-sm.hidden-md.hidden-lg
        .input-group.custom-search-form
          %input.form-control{:placeholder => "Search...", :type => "text"}/
          %span.input-group-btn
            %button.btn.btn-default{:type => "button"}
              %i.fa.fa-search
        / /input-group
      %li.nav-small-cap Main Menu
      %li
        = link_to backend_dashboard_path do
          %i.glyphicon.glyphicon-fire.fa-fw
          Dashboard
      - if can? :read, :dashboard
        %li
          = link_to backend_donations_path do
            %i.fa.fa-plane.fa-fw
            Donations
      - if user_signed_in?
        - if can? :read, :user
          %li
            = link_to backend_users_path do
              %i.fa.fa-user-circle.fa-fw
              Users
        - if can? :read, :charity_location
          %li
            = link_to backend_charity_locations_path do
              %i.fa.fa-plane.fa-fw
              Donation Location
        - if can? :read, :package_cost
          %li
            = link_to backend_package_costs_path do
              %i.fa.fa-plane.fa-fw
              Package cost
        

app/views/shared/_backend_topbar.html.haml
%nav.navbar.navbar-default.navbar-static-top{:style => "margin-bottom: 0"}
  .navbar-header
    %a.navbar-toggle.hidden-sm.hidden-md.hidden-lg{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", href: "#"}
      %i.ti-menu
    .top-left-part
      %a.logo{href: "/"}
        %i.glyphicon.glyphicon-fire>
        \ 
        %span.hidden-xs Donations
    %ul.nav.navbar-top-links.navbar-left.hidden-xs
      %li
        %a.open-close.hidden-xs.waves-effect.waves-light{:href => "javascript:void(0)"}
          %i.fa.fa-arrow-circle-left.ti-menu
      %li.dropdown
        %a.dropdown-toggle.waves-effect.waves-light{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-envelope
          %span.badge.badge-xs.badge-warning 5
        %ul.dropdown-menu.mailbox
          %li
            .drop-title You have 5 new messages
          %li
            .message-center
              %a{:href => "#"}
                .user-img
                  = image_tag 'users/pawandeep.jpg', class: 'img-circle', alt: 'User'
                  %span.profile-status.online.pull-right
                .mail-contnet
                  %h5 Pavan kumar
                  %span.mail-desc Just see the my admin!
                  %span.time 9:30 AM
              %a{:href => "#"}
                .user-img
                  = image_tag 'users/sonu.jpg', class: 'img-circle', alt: 'User'
                  %span.profile-status.busy.pull-right
                .mail-contnet
                  %h5 Sonu Nigam
                  %span.mail-desc I've sung a song! See you at
                  %span.time 9:10 AM
              %a{:href => "#"}
                .user-img
                  = image_tag 'users/arijit.jpg', class: 'img-circle', alt: 'User'
                  %span.profile-status.away.pull-right
                .mail-contnet
                  %h5 Arijit Sinh
                  %span.mail-desc I am a singer!
                  %span.time 9:08 AM
              %a{:href => "#"}
                .user-img
                  = image_tag 'users/pawandeep.jpg', class: 'img-circle', alt: 'User'
                  %span.profile-status.offline.pull-right
                .mail-contnet
                  %h5 Pavan kumar
                  %span.mail-desc Just see the my admin!
                  %span.time 9:02 AM
          %li
            %a.text-center{:href => "javascript:void(0);"}
              %strong See all notifications
              %i.fa.fa-angle-right
        / /.dropdown-messages
      / /.dropdown
      %li.dropdown
        %a.dropdown-toggle.waves-effect.waves-light{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-pencil-square-o
          %span.badge.badge-xs.badge-danger 5
        %ul.dropdown-menu.dropdown-tasks
          %li
            %a{:href => "#"}
              %div
                %p
                  %strong Task 1
                  %span.pull-right.text-muted 40% Complete
                .progress.progress-striped.active
                  .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 40%"}
                    %span.sr-only 40% Complete (success)
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %p
                  %strong Task 2
                  %span.pull-right.text-muted 20% Complete
                .progress.progress-striped.active
                  .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
                    %span.sr-only 20% Complete
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %p
                  %strong Task 3
                  %span.pull-right.text-muted 60% Complete
                .progress.progress-striped.active
                  .progress-bar.progress-bar-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%"}
                    %span.sr-only 60% Complete (warning)
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %p
                  %strong Task 4
                  %span.pull-right.text-muted 80% Complete
                .progress.progress-striped.active
                  .progress-bar.progress-bar-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
                    %span.sr-only 80% Complete (danger)
          %li.divider
          %li
            %a.text-center{:href => "#"}
              %strong See All Tasks
              %i.fa.fa-angle-right
        / /.dropdown-tasks
      / /.dropdown
      %li.dropdown
        %a.dropdown-toggle.waves-effect.waves-light{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-bell-o
          %span.badge.badge-xs.badge-info 5
        %ul.dropdown-menu.dropdown-alerts
          %li
            %a{:href => "#"}
              %div
                %i.ti-comments.fa-fw
                New Comment
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %i.ti-twitter.fa-fw
                3 New Followers
                %span.pull-right.text-muted.small 12 minutes ago
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %i.ti-email.fa-fw
                Message Sent
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %i.ti-pencil-alt.fa-fw
                New Task
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            %a{:href => "#"}
              %div
                %i.ti-upload.fa-fw
                Server Rebooted
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            %a.text-center{:href => "#"}
              %strong See All Alerts
              %i.fa.fa-angle-right
        / /.dropdown-alerts
    %ul.nav.navbar-top-links.navbar-right.pull-right
      %li
        %form.app-search.hidden-xs{:role => "search"}
          %input.form-control{:placeholder => "Search...", :type => "text"}/
          %a{href: "#"}
            %i.fa.fa-search
      %li.dropdown
        %a.dropdown-toggle.profile-pic{"data-toggle" => "dropdown", href: "#"}
          = image_tag current_user.image.url, alt: 'user-img', width: 36
          %b.hidden-xs.username= current_user.fullname.titleize
        %ul.dropdown-menu.dropdown-user
          %li
            = link_to backend_profile_path do
              %i.ti-user
              My Profile
          %li
            %a{href: "#"}
              %i.ti-email
              Inbox
          %li.divider{:role => "separator"}
          %li
            = link_to backend_profile_path(anchor: 'settings') do
              %i.ti-settings
              Account Setting
          %li.divider{:role => "separator"}
          %li
            = link_to destroy_user_session_path, data: {method: :delete, confirm: 'Are you sure to Logout?'} do
              %i.fa.fa-power-off
              Logout

app/views/shared/_flash_messages.html.haml
- if flash
  - flash.each do |type, message|
    %div{class: "text-center alert #{alert_class_for(type)} alert-dismissible", role: "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %strong
        = type.humanize
        !
      = message