config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  devise_for :users

  namespace :backend do
    root to: 'dashboard#index'
    get :dashboard, to: 'dashboard#index'
    resource :profile, only: [:show, :update, :destroy] do
      get :account_setting
    end
    resources :charity_locations do
      resources :charities
    end

    resources :package_costs

    resources :donations do
      get "sync" => "donations#sync", as: :sync
    end

    resources :users do
      member do
        post :notification_modal
        post :push_notification
      end
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',  controllers: {
        confirmations:      'devise_overrides/confirmations',
        passwords:          'devise_overrides/passwords',
        omniauth_callbacks: 'devise_overrides/omniauth_callbacks',
        registrations:      'devise_overrides/registrations',
        sessions:           'devise_overrides/sessions',
        token_validations:  'devise_overrides/token_validations'
      }

      controller :registrations do
        post :facebook, path: 'auth/facebook'
        post :twitter, path: 'auth/twitter'
      end

      resource :profile, only: [:show, :update] do
        collection do
        end
      end

      resources :addresses do
        collection do
        end
      end

      resources :donations do
        collection do
          get :total_donations, path: "total"
        end
      end

      resources :charity_locations, only: [:index] do
        collection do
          resources :charities
          get 'charities' => 'charities#index' 
        end
      end


      resources :donation_categories, only: [:index] do
        collection do
        end
      end

      resources :package_costs, only: [:index] do
        collection do
        end
      end

    end
    match "*path", to: "base#render_endpoint_not_exists", via: :all
  end

  controller :home do
    get :welcome, path: 'pages/welcome'
  end

  # match "*path", to: "home#render_404", via: :get
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  pg_search_scope :index_search, :against => [:name, :fullname, :email], :using => [:tsearch]
  VALID_ROLES = %w(admin user customer editor).freeze
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  include DeviseTokenAuth::Concerns::User
  has_attached_file :image, style: {medium: {geometry: '500x500>'}, thumb: '150x150>'}, default_url: ApplicationController.helpers.asset_path("default_avatar.png")
  #=================================================================================================
  # ASSOCCIATIONS
  #=================================================================================================
  has_many :devices, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :donations, dependent: :destroy
  #=================================================================================================
  # VALIDATIONS
  #=================================================================================================
  validates :role, inclusion: VALID_ROLES
  #validates :phone, numericality: { only_integer: true, allow_nil: true, allow_blank: true }, on: :update
  validates_attachment_size :image, less_than: 10.megabytes
  validates_attachment_content_type :image, content_type: /\Aimage/
  #=================================================================================================
  # METHODS
  #=================================================================================================
  (VALID_ROLES).each do |role|
    define_method("#{role}?") do
      self.role == role
    end
    scope role, -> { where(role: role) }
  end

  

  def as_json(options = nil)
    response_json = super
    response_json.merge!(image_url: self.image.try(:url))
  end

 
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout 'backend'
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do
    redirect_to backend_profile_path, alert: 'Your dont have permission to view this page'
  end
end

app/controllers/backend/charities_controller.rb
class Backend::CharitiesController < Backend::BaseController
  authorize_resource
  before_action :set_charity, only: [:show, :edit, :update, :destroy]
  before_action :set_charity_location, only: [:new, :edit, :update, :show, :destroy, :create]

  # GET /backend/charities
  # GET /backend/charities.json
  def index
    @backend_charities = Charity.all
  end

  # GET /backend/charities/1
  # GET /backend/charities/1.json
  def show
  end

  # GET /backend/charities/new
  def new
    @charity = @charity_location.charities.new
  end

  # GET /backend/charities/1/edit
  def edit
  end

  # POST /backend/charities
  # POST /backend/charities.json
  def create
    @charity = @charity_location.charities.new(charity_params)

    respond_to do |format|
      if @charity.save
        format.html { redirect_to backend_charity_location_url(@charity.charity_location), notice: 'Charity was successfully created.' }
        format.json { render :show, status: :created, location: @charity }
      else
        format.html { render :new }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backend/charities/1
  # PATCH/PUT /backend/charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to backend_charity_location_url(@charity.charity_location), notice: 'Charity was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity }
      else
        format.html { render :edit }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/charities/1
  # DELETE /backend/charities/1.json
  def destroy
    @charity_location = @charity.charity_location
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to backend_charity_location_url(@charity_location), notice: 'Charity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      
      @charity = Charity.find(params[:id])
    end

    def set_charity_location
      @charity_location = CharityLocation.find params[:charity_location_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:name, :status)
    end
end

app/controllers/backend/charity_locations_controller.rb
class Backend::CharityLocationsController < Backend::BaseController

  before_action :authenticate_user!
  before_action :set_backend_charity_location, only: [:show, :edit, :update, :destroy]

  # GET /backend/donation_locations
  # GET /backend/donation_locations.json
  def index
    @charity_locations = CharityLocation.all
  end

  # GET /backend/donation_locations/1
  # GET /backend/donation_locations/1.json
  def show
  end

  # GET /backend/donation_locations/new
  def new
    @charity_location = CharityLocation.new
  end

  # GET /backend/donation_locations/1/edit
  def edit
  end

  # POST /backend/donation_locations
  # POST /backend/donation_locations.json
  def create
    @charity_location = CharityLocation.new(backend_charity_location_params)

    respond_to do |format|
      if @charity_location.save
        format.html { redirect_to backend_charity_location_url(@charity_locations), notice: 'Donation location was successfully created.' }
        format.json { render :show, status: :created, location: backend_charity_location_url(@charity_location) }
      else
        format.html { render :new }
        format.json { render json: @charity_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backend/donation_locations/1
  # PATCH/PUT /backend/donation_locations/1.json
  def update
    respond_to do |format|
      if @charity_location.update(backend_charity_location_params)
        format.html { redirect_to backend_charity_location_url(@charity_location), notice: 'Donation location was successfully updated.' }
        format.json { render :show, status: :ok, location: backend_charity_location_url(@charity_location) }
      else
        format.html { render :edit }
        format.json { render json: @charity_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/donation_locations/1
  # DELETE /backend/donation_locations/1.json
  def destroy
    @charity_location.destroy
    respond_to do |format|
      format.html { redirect_to backend_charity_locations_url, notice: 'Donation location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backend_charity_location
      @charity_location = CharityLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backend_charity_location_params
      params.require(:charity_location).permit(:id, :location_name, :status)
    end
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
  before_action :authenticate_user!

  def index
  	@total_donations = Donation.all.count
  	@total_users = User.all.count
  	@total_charities = Charity.all.count
  end
end

app/controllers/backend/donations_controller.rb
class Backend::DonationsController < Backend::BaseController
  authorize_resource
  before_action :set_donation, only: [:show, :edit, :update, :destroy, :sync]

  # GET /backend/donations
  # GET /backend/donations.json
  def index
    donations = Donation.includes(:user).includes(:charity).includes(:package_cost).includes(:address).all.order(id: :desc)
    donations = donations.page(paging_params[:page]).per(paging_params[:per])
    @donations = donations
  end

  # GET /backend/donations/1
  # GET /backend/donations/1.json
  def show
  end

  def sync
    SyncDonationJobJob.perform_async  @donation.id
    respond_to do |format|
      format.html { redirect_to backend_donations_url, notice: 'Donation was successfully destroyed.' }
    end
  end

  # GET /backend/donations/new
  def new
    @donaton = Donation.new
  end

  # GET /backend/donations/1/edit
  def edit
  end

  # POST /backend/donations
  # POST /backend/donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        SyncDonationJobJob.perform_async  @donation.id
        @donation.donation_categories = DonationCategory.where(id: params[:donation][:donation_category_ids])

        format.html { redirect_to backend_donation_url(@donation), notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: backend_donation_url(@donation) }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backend/donations/1
  # PATCH/PUT /backend/donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        @donation.donation_categories = DonationCategory.where(id: params[:donation][:donation_category_ids])
        format.html { redirect_to backend_donation_url(@donation), notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/donations/1
  # DELETE /backend/donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to backend_donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation =Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:user_id, :charity_id, :package_cost_id, :address_id, :total_price, :number_of_cartons,
        :is_fragile, :wimo_task_id, donation_category_ids: [],  attachments_attributes: [:id, :file, :_destroy])
    end

    def attachment_params
      params.require(:attachment).permit(:file)
    end
end

app/controllers/backend/package_costs_controller.rb
class Backend::PackageCostsController < Backend::BaseController
  authorize_resource
  before_action :set_package_cost, only: [:show, :edit, :update, :destroy]

  # GET /backend/package_costs
  # GET /backend/package_costs.json
  def index
    @package_costs = PackageCost.all
  end

  # GET /backend/package_costs/1
  # GET /backend/package_costs/1.json
  def show
  end

  # GET /backend/package_costs/new
  def new
    @package_cost = PackageCost.new
  end

  # GET /backend/package_costs/1/edit
  def edit
  end

  # POST /backend/package_costs
  # POST /backend/package_costs.json
  def create
    @package_cost = PackageCost.new(package_cost_params)

    respond_to do |format|
      if @package_cost.save
        format.html { redirect_to backend_package_cost_url(@package_cost), notice: 'Package cost was successfully created.' }
        format.json { render :show, status: :created, location: @package_cost }
      else
        format.html { render :new }
        format.json { render json: @package_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backend/package_costs/1
  # PATCH/PUT /backend/package_costs/1.json
  def update
    respond_to do |format|
      if @package_cost.update(package_cost_params)
        format.html { redirect_to backend_package_cost_url(@package_cost), notice: 'Package cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @package_cost }
      else
        format.html { render :edit }
        format.json { render json: @package_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/package_costs/1
  # DELETE /backend/package_costs/1.json
  def destroy
    @package_cost.destroy
    respond_to do |format|
      format.html { redirect_to backend_package_costs_url, notice: 'Package cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_cost
      @package_cost = PackageCost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_cost_params
      params.require(:package_cost).permit(:package_size, :cost_per_carton)
    end
end

app/controllers/backend/profiles_controller.rb
class Backend::ProfilesController < Backend::BaseController
  def show
  end

  def update
    if current_user.update_attributes(user_params)
      render :show, notice: 'Profile updated'
    else
      render :show, alert: 'Failed to update profile, please check your input'
    end
  end

  def account_setting
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :phone, :gender, :company_name, :organisation, :website)
  end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::BaseController
  authorize_resource
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    users = User.all
    users = users.index_search(params[:q]) if params[:q].present?
    users = users.page(paging_params[:page]).per(paging_params[:per])
    @users = users
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="users_export_'+ Time.now.strftime("%d_%b_%Y") +'.xlsx"'
      }
    end
  end

  def new
    @user = User.new
  end

  def show
  end

  def notification_modal
    @user = User.find params[:id]
    respond_to do |format|
      format.js
    end
  end

  def push_notification
    @user = User.find params[:id]
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to({ action: 'index' }, alert: "User created")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to({action: :index}, notice: 'User updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to({action: :index}, alert: 'User destroyed')
  end


  private

  def find_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :surname, :email, :role)
  end

end

app/helpers/backend/charities_helper.rb
module Backend::CharitiesHelper
end

app/helpers/backend/donation_locations_helper.rb
module Backend::DonationLocationsHelper
end

app/helpers/backend/donations_helper.rb
module Backend::DonationsHelper
end

app/helpers/backend/package_costs_helper.rb
module Backend::PackageCostsHelper
end

app/views/backend/users/_form.html.haml
= simple_form_for ['backend', @user] do |f|
  .row
    .col-sm-6
      = f.input :fullname
  .row
    .col-sm-6
      = f.input :email
    .col-sm-6
      = f.input :role, collection: User::VALID_ROLES
  = f.submit nil, class: 'btn btn-sm btn-success'
  = link_to 'Back', :back, class: 'btn btn-sm btn-warning'

app/views/backend/users/_notification_modal.html.haml
.push-notification-modal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      = form_tag push_notification_backend_user_path(@user), method: :post, remote: true do
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4.modal-title Send notification to #{@user.full_name}
        .modal-body
          .form-group
            %label Message
            = text_field_tag :message, nil, class: 'form-control'
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          %button.btn.btn-primary{:type => "submit"} Send

app/views/backend/users/edit.html.haml
.row.bg-title
  .col-lg-12
    %h4.page-title User management
    %ol.breadcrumb
      %li
        %a{:href => "/"} Dashboard
      %li
        = link_to 'Users', backend_users_path
      %li.active All users
  / /.col-lg-12
/ row
.row
  .col-lg-12
    .white-box
      %h3 Edit user
      = render partial: 'form'

app/views/backend/users/index.html.haml
.row.bg-title
  .col-lg-12
    %h4.page-title User management
    %ol.breadcrumb
      %li
        %a{:href => "/"} Dashboard
      %li
        = link_to 'Users', backend_users_path
      %li.active All users
  / /.col-lg-12
/ row
.row
  .col-lg-12
    .white-box
      %h3 Listing users
      .box-header.row
        .col-md-6
          = form_tag backend_users_path, method: :get, class: 'form-inline' do
            .form-group
              = text_field_tag :q, nil,  placeholder: 'Search anything', class: 'form-control'
            = button_tag 'Search', type: 'submit', class: 'btn btn btn-success'
        .col-md-6
          .btn-group.pull-right
            = link_to new_backend_user_path, class: 'btn btn-success' do
              %i.fa.fa-plus
              New user
            
      .table-responsive
        %table.table.table-hover.table-striped.table-bordered
          %thead
            %tr
              %th #
              %th Name
              %th Email
              %th Role
              %th Action...
          %tbody
            - @users.each do |user|
              %tr
                %td= user.id
                %td= user.fullname.try :humanize
                %td
                  = link_to user.email, "maito:#{user.email}"
                %td
                  %span.label{class: label_class_for(user.role)}= user.role
                %td
                  .btn-group
                    = link_to edit_backend_user_path(user), class: "btn btn-primary btn-sm" do
                      %i.fa.fa-pencil
                      Edit
                    = link_to backend_user_path(user), class: "btn btn-success btn-sm" do
                      %i.fa.fa-user
                      Show
                    = link_to backend_user_path(user), data: {method: 'delete', confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" do
                      %i.fa.fa-trash
                      Destroy
                   
      .push-notification
      = paginate @users

app/views/backend/users/new.html.haml
.row.bg-title
  .col-lg-12
    %h4.page-title User management
    %ol.breadcrumb
      %li
        %a{:href => "/"} Dashboard
      %li
        = link_to 'Users', backend_users_path
      %li.active All users
  / /.col-lg-12
/ row
.row
  .col-lg-12
    .white-box
      %h3 New user
      = render partial: 'form'

app/views/backend/users/notification_modal.js.erb
$('.push-notification').html("<%= j render 'backend/users/notification_modal' %>")
$('.push-notification-modal').modal('show');

app/views/backend/users/push_notification.js.erb
$('.push-notification-modal').modal('hide');

app/views/backend/users/show.html.haml
.row.bg-title
  .col-lg-12
    %h4.page-title User management
    %ol.breadcrumb
      %li
        %a{:href => "/"} Dashboard
      %li
        = link_to 'Users', backend_users_path
      %li.active User details
  / /.col-lg-12
/ row
.row
  .col-lg-12
    .white-box
      %h3= @user.fullname
      %h5= @user.email
      %p= @user.created_at.strftime('%a %m-%d-%Y at %H:%M %P')
      = link_to 'Back', :back, class: 'btn btn-sm btn-warning'